FROM ruby:2.6-alpine

# install redis
RUN apk update && apk add \
  make gcc libc-dev bash \
  redis \
  dcron \
  && rm -rf /var/cache/apk/*

## CRON
COPY ptp-cron /etc/cron.d/ptp-cron
RUN chmod 0644 /etc/cron.d/ptp-cron
RUN crontab /etc/cron.d/ptp-cron

## PTP-NOTIFIER
RUN bundle config --global frozen 1
WORKDIR /usr/src/app
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENTRYPOINT ["./entrypoint.sh"]
CMD ["./start.sh"]
